externalHostname: "kcp.example.com"
etcd:
  enabled: true
  image: quay.io/coreos/etcd
  tag: v3.5.4
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      # cpu: 1
     memory: 20Gi
  volumeSize: 8Gi
  profiling:
    enabled: false
kcp:
  image: ghcr.io/kcp-dev/kcp
  tag: latest
  pullPolicy: Always
  v: "3"
  logicalClusterAdminFlag: true
  externalLogicalClusterAdminFlag: true
  resources:
    requests:
      memory: 5Gi
      cpu: 100m
    limits:
      # cpu: 1
      memory: 20Gi
  volumeClassName: gp2-csi
  etcd:
    serverAddress: https://etcd:2379
    clientCertificate:
      issuer: etcd-client-issuer
      commonName: root
  volumeSize: 1Gi
  extraFlags: []
  profiling:
    enabled: false
    port: 6060
  tokenAuth:
    enabled: false
    fileName: auth-token.csv
    config: |
        user-1-token,user-1,1111-1111-1111-1111,"team-1"
        admin-token,admin,5555-5555-5555-5555,"system:kcp:admin"
        system-token,system,6666-6666-6666-6666,"system:masters"
  hostAliases:
    enabled: false
  homeWorkspaces:
    enabled: false
kcpFrontProxy:
  image: ghcr.io/kcp-dev/kcp
  tag: latest
  pullPolicy: Always
  v: "4"
  shardsKubeConfigFlag: true
  openshiftRoute:
    enabled: false
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
      acme.cert-manager.io/http01-edit-in-place: "true"
      # this is ingress-controller-specific and might need configuration
      # depending on the ingress-controller in use.
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    secret: ""
  gateway:
    enabled: false
    className: ""
  service:
    annotations: {}
    # set this to LoadBalancer if you want to publish kcp-front-proxy
    # directly instead of going via Route/Ingress/Gateway resources.
    type: ClusterIP
  certificate:
    issuer: kcp-ca
    # if Let's Encrypt is used, this should be ClusterIssuer.
    issuerKind: Issuer
  profiling:
    enabled: false
    port: 6060
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      # cpu: 1
      memory: 1Gi
  hostAliases:
    enabled: false
oidc:
  enabled: false
audit:
  enabled: false
  volumeSize: 1Gi
  volumeClassName: "gp2-csi"
  policy:
    dir: /etc/kcp/audit
    fileName: audit-policy.yml
    config: |
      # Log all requests at the Metadata level.
      apiVersion: audit.k8s.io/v1
      kind: Policy
      rules:
      - level: Metadata
  log:
    maxAge: "10"
    maxSize: "250"
    maxBackup: "1"
    dir: /var/audit
certificates:
  privateKeys:
    algorithm: RSA
    size: 2048
  subject: {}
  dnsNames:
  - kcp
  - localhost
githubUserEditAccess:
- test
letsEncrypt:
  enabled: false
  staging:
    enabled: false
    email: ""
  production:
    enabled: false
    email: ""
